### ISSUE TITLE
updating problem

### ISSUE THREAD

**Issue by UNdeng** [ramafeichu/TD-PSOLA_C#1]
Hello sir,
Do you still update the TD_PSOLA project?
Thank you

**Comment by Sir-Branch** [comment]
Hi UNdeng, 

Unfortunately this project isn't maintained, and **doesn't work as intented!** This is a shelved attempt at running PSOLA in C.
If you' re going to go down this road I'd look into using C++ and a linear algebra library like Eigen.

Best of luck,

**Comment by UNdeng** [comment]
thanks for your reply, I want to know what a linear algebra library can be used to ADSP, or MCU platform.

**Comment by UNdeng** [comment]
> Hi UNdeng,
> 
> Unfortunately this project isn't maintained, and **doesn't work as intented!** This is a shelved attempt at running PSOLA in C.
> If you' re going to go down this road I'd look into using C++ and a linear algebra library like Eigen.
> 
> Best of luck,

**Comment by UNdeng** [comment]
thanks for your reply, I want to know what a linear algebra library can be used to ADSP, or MCU platform in C language.
